name: Build and test

on:
  push:
    branches: master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-version: "22.4"

      - name: Install
        run: npm install

      - name: Build and test project
        run: npx spago test
